
package de.tuberlin.techgi4.gpscalcwebservice;


import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "GPSCalc", targetNamespace = "http://gpscalcWebservice.techgi4.tuberlin.de/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface GPSCalc {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sayHello", targetNamespace = "http://gpscalcWebservice.techgi4.tuberlin.de/", className = "de.tuberlin.techgi4.gpscalcwebservice.SayHello")
    @ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "http://gpscalcWebservice.techgi4.tuberlin.de/", className = "de.tuberlin.techgi4.gpscalcwebservice.SayHelloResponse")
    @Action(input = "http://gpscalcWebservice.techgi4.tuberlin.de/GPSCalc/sayHelloRequest", output = "http://gpscalcWebservice.techgi4.tuberlin.de/GPSCalc/sayHelloResponse")
    public String sayHello(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns de.tuberlin.techgi4.gpscalcwebservice.CoordinateVector
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getDistance", targetNamespace = "http://gpscalcWebservice.techgi4.tuberlin.de/", className = "de.tuberlin.techgi4.gpscalcwebservice.GetDistance")
    @ResponseWrapper(localName = "getDistanceResponse", targetNamespace = "http://gpscalcWebservice.techgi4.tuberlin.de/", className = "de.tuberlin.techgi4.gpscalcwebservice.GetDistanceResponse")
    @Action(input = "http://gpscalcWebservice.techgi4.tuberlin.de/GPSCalc/getDistanceRequest", output = "http://gpscalcWebservice.techgi4.tuberlin.de/GPSCalc/getDistanceResponse")
    public CoordinateVector getDistance(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        GpsCoordinates arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getOtherClientIdin", targetNamespace = "http://gpscalcWebservice.techgi4.tuberlin.de/", className = "de.tuberlin.techgi4.gpscalcwebservice.GetOtherClientIdin")
    @ResponseWrapper(localName = "getOtherClientIdinResponse", targetNamespace = "http://gpscalcWebservice.techgi4.tuberlin.de/", className = "de.tuberlin.techgi4.gpscalcwebservice.GetOtherClientIdinResponse")
    @Action(input = "http://gpscalcWebservice.techgi4.tuberlin.de/GPSCalc/getOtherClientIdinRequest", output = "http://gpscalcWebservice.techgi4.tuberlin.de/GPSCalc/getOtherClientIdinResponse")
    public List<String> getOtherClientIdin(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        double arg1);


}
