
package de.tuberlin.techgi4.gpscalcwebservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "GPSCalcImplService", targetNamespace = "http://gpscalcWebservice.techgi4.tuberlin.de/", wsdlLocation = "http://localhost:8080/WS/Greeting?wsdl")
public class GPSCalcImplService
    extends Service
{

    private final static URL GPSCALCIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException GPSCALCIMPLSERVICE_EXCEPTION;
    private final static QName GPSCALCIMPLSERVICE_QNAME = new QName("http://gpscalcWebservice.techgi4.tuberlin.de/", "GPSCalcImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/WS/Greeting?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        GPSCALCIMPLSERVICE_WSDL_LOCATION = url;
        GPSCALCIMPLSERVICE_EXCEPTION = e;
    }

    public GPSCalcImplService() {
        super(__getWsdlLocation(), GPSCALCIMPLSERVICE_QNAME);
    }

    public GPSCalcImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), GPSCALCIMPLSERVICE_QNAME, features);
    }

    public GPSCalcImplService(URL wsdlLocation) {
        super(wsdlLocation, GPSCALCIMPLSERVICE_QNAME);
    }

    public GPSCalcImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, GPSCALCIMPLSERVICE_QNAME, features);
    }

    public GPSCalcImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GPSCalcImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns GPSCalc
     */
    @WebEndpoint(name = "GPSCalcImplPort")
    public GPSCalc getGPSCalcImplPort() {
        return super.getPort(new QName("http://gpscalcWebservice.techgi4.tuberlin.de/", "GPSCalcImplPort"), GPSCalc.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GPSCalc
     */
    @WebEndpoint(name = "GPSCalcImplPort")
    public GPSCalc getGPSCalcImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://gpscalcWebservice.techgi4.tuberlin.de/", "GPSCalcImplPort"), GPSCalc.class, features);
    }

    private static URL __getWsdlLocation() {
        if (GPSCALCIMPLSERVICE_EXCEPTION!= null) {
            throw GPSCALCIMPLSERVICE_EXCEPTION;
        }
        return GPSCALCIMPLSERVICE_WSDL_LOCATION;
    }

}
